vrrp_instance haproxy-vip {

    interface eth0
    state MASTER
    priority 100
    virtual_router_id 1

    unicast_src_ip [ip lb-0]
    unicast_peer {
      [ip lb-1]
    }

    virtual_ipaddress {
        10.0.0.100/24
    }

}