apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: github
spec:
  interval: 1m
  url: https://github.com/trutzio/kubernetes-tutorial.git
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/src/apps/rolldice/helm/  