apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rolldice
spec:
  interval: 10m
  chart:
    spec:
      chart: src/apps/rolldice/helm/rolldice
      sourceRef:
        kind: GitRepository
        name: github
      interval: 10m
