apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
  accessModes:
    - ReadWriteOncePod # siehe auch https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi