apiVersion: apps/v1
kind: StatefulSet	
metadata:
  name: postgres
spec:
  replicas: 1
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: "postgres-container"
        image: "postgres:18.3-alpine3.23"
        env:
        - name: POSTGRES_PASSWORD
          value: "secret"
        #envFrom:
        #- configMapRef:
        #    name: postgres
        #- secretRef:
        #    name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres
        
        