apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: schulungk8s
spec:
  refreshInterval: 0h1m0s
  secretStoreRef:
    kind: SecretStore
    name: schulungk8s
  target:
    name: postgres
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: postgres-secret