apiVersion: v1
kind: Secret
metadata:
  name: azure
data:
  ClientID: "..." # echo -n "..." | base64 --- Base64 encoded value of the Service Principal client ID
  ClientSecret: "..." # echo -n "..." | base64 --- Base64 encoded value of the Service Principal client secret