apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: schulungk8s
spec:
  provider:
    azurekv:
      # URL of your Key Vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "https://schulungk8s.vault.azure.net"
      # Azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: "0311ed83-55eb-476b-8d8e-8e04b668903f"
      authSecretRef:
        # Reference to Kubernetes Secret name containing the Service Principal client ID under the key `ClientID`
        clientId:
          name: azure-secrets
          key: ClientID
        # Reference to Kubernetes Secret name containing the Service Principal client secret under the key `ClientSecret`
        clientSecret:
          name: azure-secrets
          key: ClientSecret